### ISSUE TITLE
Using dlputils

### ISSUE THREAD

**Issue by MohammedUI** [trisyoungs/dlputils#1]
Hello all,

I'm using dlputils to analyses my simulations. I have a problem with the use of counthb (hydrogen bond calculations), I could not figure out the exact command.  I would like to calculate h-bonds between species 1 molecules, In my system, the donor is atom #55 and the acceptor is atom #56, thus I used this command:
counthb HISTORY OUTPUT 1 -55 1 -56  but didn't work and gives this error: STOP Error: No XH sites defined on species 1.
In addition, the units of most of the codes results are not defined. For diffusion coefficient, is there any code to calculate it? and is there any code to calculate interaction energies for specific species (such as vdW interactions between species 1 molecules)? 

Thanks 
Mohammed

**Comment by trisyoungs** [comment]
Hi Mohammed,

To use counthb to detect an interaction X-H...Y you must supply the indices of all three involved atoms, X, H, and Y.  So in your case H is index 55, Y is index 56, and X is whichever atom is bound to your H (55). You also need to provide the maximum H...Y distance you are interested in (say 3.0 Angstroms) and the minimum X-H...Y angle you will accept (perhaps 150.0 degrees). All your sites are on species 1 in your simulation, so the full command would be:

counthb HISTORY OUTPUT 1 1 3.0 150.0 -xh X 55 -y 56

...where X is the atom index of your X atom.

For your second question, which units in particular are you referring to? The unit of distance is always Angstroms.

If you want to calculate diffusion coefficients, look at the msd code. Finally, if you want to calculate interaction energies you can do this within DL_POLY - (in DL_CLASS_1.9 look in Chapter 6 - Solvation).

**Comment by MohammedUI** [comment]
Hello all, 
Thank you. I have used most of the codes to calculate my needs. 
For diffusion coefficient, I calculated msd as the distance unit is Angstrom and time unit is a picosecond but the results were far from experimental data. I tried several times and the slope was same, I dont know if I did something wrong.

**Comment by trisyoungs** [comment]
Be careful - the deltat parameter given to msd is the delta t between frames in the trajectory file, rather than the timestep of the simulation itself.  Perhaps this explains the discrepancy?

**Comment by MohammedUI** [comment]
Something is going wrong, delta t should not have an effect on the results (my time step is 2fs and I chose different delta t). The slope which is diffusion coefficient should have the units of Ang/ps and doing units conversions, I got different results from the experimental data. I think the polt should be simulation time vs msd to get accurate results

**Comment by trisyoungs** [comment]
The time elapsed between frames in your trajectory file *will* have an effect on the result, and this is the "delta t" that the msd code needs. The slope of the msd output will have units of Angstroms/delta T. Also, the slope of the linear regime of the calculated MSD is *related* to the diffusion coefficient, rather than being the diffusion coefficient itself. You still need to account for the dimensionality of your system: D = MSD / 2n, where 'n' is the dimensionality (probably 3).

**Comment by MohammedUI** [comment]
I see. That means I need to divide my slope by 3 and do units conversions. 
What do you suggest about a better delta t? I used 0.02 ps and could not get close results.

**Comment by trisyoungs** [comment]
You should divide by 6 (2n) assuming that your simulation is three-dimensional. The delta t you give to msd should be your simulation timestep multiplied by the frequency that your trajectory file was written at (specified in your CONTROL file).  There are lots of other reasons why your actual diffusion coefficient may not match with experiment: Are you taking the slope from a well-defined linear part of the MSD?  Is your simulation equilibrated?  Is your forcefield "accurate"?  Are the experimental values dependable?

**Comment by MohammedUI** [comment]
Ok, there is something wrong with delta t. I'm saving the trajectory every 5000 steps and the timestep is 0.002 ps, thus delta t should be 10 (5000x0.002). This should give a plot of MSD vs simulation time according to saved frames (10, 20, 30, ... ps) but what I got is (0.00001, 0.00002. 0.00003, ...). If I multiply time axis by 10e5 then I get close results. 
My system is n-heptane and I use oplsaa ff which is proved to reproduce experimental data of liquid hydrocarbons. The system is well equilibrated and I calculate the slope from well linear part.

**Comment by trisyoungs** [comment]
Try providing your timestep between frames (10) as a real number (10.0) - it will likely get misinterpreted otherwise. Converting strings to numbers in Fortran is not handled well!

**Comment by MohammedUI** [comment]
Hello again, 
Is there any way to calculate the diffusion coefficient for the whole system (the system has 3 species)? 
I'm trying to calculate and compare the viscosity of my systems, is there any script that calculates the viscosity from DL_POLY data? 
Thank you

**Comment by trisyoungs** [comment]
There is currently no option in the code to calculate the combined diffusion coefficient of multiple species in the system - the output will always be separated by species.  You can either do a weighted average of the three components, or modify the code to calculate the combined MSD.

Regarding viscosity, there is no dlputil for that - sorry!
